### ISSUE TITLE
Icons Requests

### ISSUE THREAD

**Issue by arunsankars1989** [synthagency/icons-flat-osx#100]
Please add "Smart Git" icon

**Comment by warmmorningwood** [comment]
Please add "Stardew Valley" game icon

**Comment by thejasonparker** [comment]
Please add the following icons...

aText
Figma
Hidden Bar
Local by Flywheel
Microsoft Visual Studio Code

Thank you :)

**Comment by synthagency** [comment]
Moved to discussion https://github.com/synthagency/icons-flat-osx/discussions
