### ISSUE TITLE
App SnippetsLab

### ISSUE THREAD

**Issue by Kraddle** [synthagency/icons-flat-osx#76]
Hey !
Awesome job !
But i want more , again   ;)

SnippetsLab:
https://www.renfei.org/snippets-lab/

Thanks
Best Regards.

**Comment by synthagency** [comment]
Hi, thx for feedback! added icon.
Best regards

**Comment by Kraddle** [comment]
Hi. Nice job. I don't find it
Regards
Kraddle

--
Fred

**Comment by synthagency** [comment]
You're too fast, just pushed it ;)

**Comment by Kraddle** [comment]
Sorry. I  was in a hurry 😀
Thanks for your amazing job

--
Fred
