### ISSUE TITLE
Request icon for Script Debugger

### ISSUE THREAD

**Issue by artdevjs** [synthagency/icons-flat-osx#83]
Please add [Script Debugger](http://latenightsw.com/) icon.
![script debugger](https://cloud.githubusercontent.com/assets/7567983/22883392/c1731bc8-f1f8-11e6-9cb2-0562ea62d395.png)
Thanks!

**Comment by synthagency** [comment]
Added!

**Comment by artdevjs** [comment]
wow, super fast, thx! 👌
