### ISSUE TITLE
Icons request

### ISSUE THREAD

**Issue by artdevjs** [synthagency/icons-flat-osx#85]
Hey, I really like your icons, the best pack of what I've seen, thanks for the work.
I would be very grateful if you add at least something from the list:
- [Adguard](https://adguard.com/en/adguard-mac/overview.html)
- [BetterTouchTool](https://www.boastr.net/)
- [Folx](http://mac.eltima.com/download-manager.html)
- [Hammerspoon](http://www.hammerspoon.org/)
- [Karabiner](https://pqrs.org/osx/karabiner/)
- [Leaf](https://itunes.apple.com/ua/app/leaf-rss-news-reader/id576338668?mt=12)

**Comment by synthagency** [comment]
added adguard, folx, bettertouchtool & leaf, i'm planning others tommorow

**Comment by artdevjs** [comment]
Cool, thank's a lot! 🎉

**Comment by synthagency** [comment]
Added Karabiner & Hammerspoon, cheers

**Comment by artdevjs** [comment]
Thank you
