### ISSUE TITLE
Gemini 2 request

### ISSUE THREAD

**Issue by Kraddle** [synthagency/icons-flat-osx#87]
HI,
Your icons are amazing.
Thanks.

A new request icon :
[Gemini 2](https://macpaw.com/fr/gemini)

Thanks

**Comment by synthagency** [comment]
Added, (not so conviced about it, maybe modded in a few days)
Thx for feedback! :)

**Comment by Kraddle** [comment]
Great. 
Thanks a lot
--
Fred
