### ISSUE TITLE
icon requests

### ISSUE THREAD

**Issue by elogicuk** [synthagency/icons-flat-osx#88]
Hello first i want to say a big thank you for taking your time to make such an amazing icon set

i am missing a few icons

vivaldi web browser 
flume (https://flumeapp.com/)
instabro (https://instabro.boriskarulin.com/)
photobulk (http://mac.eltima.com/bulk-image-editor.html)

**Comment by technonaut** [comment]
Hello,

Was wanting to add a few more requests to this list, as your icons are truly fantastic!

- [GNS3 ](https://www.gns3.com)
- SnagIt [https://www.techsmith.com/screen-capture.html](url)

**Comment by synthagency** [comment]
@elogicuk requests online, cheers ;)

**Comment by synthagency** [comment]
@technonaut icons online, cheers ;)
