### ISSUE TITLE
Icon Request – Stockfish Chess Engine

### ISSUE THREAD

**Issue by luminousrubyist** [synthagency/icons-flat-osx#89]
Hi there! Thank you so much for creating this icon set. This will be the third (or fourth?) time that I am submitting a request, which is in itself a testament to how much I enjoy your work. I've used your icons for over a year, and I cannot say enough how fantastic they are.

I wanted to make a request for an icon for [Stockfish](https://stockfishchess.org/), a powerful open-source chess engine. Do you think you could create this icon?

Thanks so much,

-LR

**Comment by synthagency** [comment]
hi, 

really thanks for your nice comment, that's that kind of things that keep me motivated about this icon pack! :) Icon have been added!

Cheers, 
Jean
