### ISSUE TITLE
re-do visual studios OSX Icon

### ISSUE THREAD

**Issue by AbhimanyuAryan** [synthagency/icons-flat-osx#90]
Hi just noticed Visual Studio OSX is finally out of beta & they have redone the icon from 'white & blue' color to 'black & blue'

Please re-do this one :) 

<img width="53" alt="screen shot 2017-07-12 at 6 54 59 pm" src="https://user-images.githubusercontent.com/8083613/28119818-c4c88244-6733-11e7-9ae4-a57a304f3eec.png">

**Comment by synthagency** [comment]
done, cheers ;)

**Comment by AbhimanyuAryan** [comment]
you did it wrong :( 
You have removed Visual Studio Code icon 
<img width="53" alt="screen shot 2017-09-23 at 2 26 54 am" src="https://user-images.githubusercontent.com/8083613/30764013-b742cb32-a006-11e7-8280-39d7e5a66788.png">

Visual Studio Code is still same "White and sky blue"
The new icon is Visual Studio MacOS & not code :) 

@synthagency
